
export const labelMap:Record<string, string> = {
  // English
  "Book Free Consultation": "book_consultation",
  "Pregnancy Calculator": "success_calculator",
  "Find Hospital": "find_hospital",
  "FAQ's":"frequently_asked_questions",
  //"Emotional Support": "emotional_support",
  "EMI facilities": "emi_facilities",
  "Success Rate": "success_rate",
  "IVF Packages": "packages",
  "Services Offered":"services_offered",
  "Understanding IVF": "understanding_ivf",

  // Hindi
  "नि:शुल्क परामर्श बुक करें": "book_consultation",
  "गर्भावस्था कैलकुलेटर": "success_calculator",
  "अस्पताल खोजें": "find_hospital",
  "अक्सर पूछे जाने वाले प्रश्न":"frequently_asked_questions",
  //"भावनात्मक समर्थन": "emotional_support",
  "ईएमआई सुविधाएं": "emi_facilities",
  "सफलता दर": "success_rate",
  "आईवीएफ पैकेज": "packages",
  "प्रदान की जाने वाली सेवाएं":"services_offered",
  "आईवीएफ को समझना": "understanding_ivf",

  // Marathi
  "मोफत सल्लामसलत बुक करा": "book_consultation",
  "गर्भधारणा कॅल्क्युलेटर": "success_calculator",
  "रुग्णालय शोधा": "find_hospital",
  "वारंवार विचारले जाणारे प्रश्न":"frequently_asked_questions",
  //"भावनिक मदत": "emotional_support",
  "ईएमआय सुविधा": "emi_facilities",
  "यश दर": "success_rate",
  "IVF पॅकेजेस": "packages",
  "पुरवण्यात येणाऱ्या सेवा":"services_offered",
  "IVF समजून घ्या": "understanding_ivf",

  // Gujarati
  "મફત પરામર્શ બુક કરો": "book_consultation",
  "ગર્ભાવસ્થા કેલ્ક્યુલેટર": "success_calculator",
  "હૉસ્પિટલ શોધો": "find_hospital",
  "વારંવાર પૂછાતા પ્રશ્નો":"frequently_asked_questions",
  //"ભાવનાત્મક સમર્થન": "emotional_support",
  "ઈએમઆઈ સુવિધાઓ": "emi_facilities",
  "સફળતા દર": "success_rate",
  "આઈવીએફ પેકેજીસ": "packages",
  "પ્રદાન કરવામાં આવતી સેવાઓ":"services_offered",
  "આઈવીએફને સમજવું": "understanding_ivf",

  // Kannada
  "ಉಚಿತ ಸಲಹೆ ಬುಕ್ ಮಾಡಿ": "book_consultation",
  "ಗರ್ಭಾವಸ್ಥೆ ಕ್ಯಾಲ್ಕುಲೇಟರ್": "success_calculator",
  "ಆಸ್ಪತ್ರೆಯನ್ನು ಹುಡುಕಿ": "find_hospital",
  "ಪದೇ ಪದೇ ಕೇಳಲಾಗುವ ಪ್ರಶ್ನೆಗಳು":"frequently_asked_questions",
  //"ಭಾವನಾತ್ಮಕ ಬೆಂಬಲ": "emotional_support",
  "ಇಎಂಐ ಸೌಲಭ್ಯಗಳು": "emi_facilities",
  "ಯಶಸ್ಸಿನ ದರ": "success_rate",
  "ಐವಿಎಫ್ ಪ್ಯಾಕೇಜ್ಗಳು": "packages",
  "ಒದಗಿಸಲಾದ ಸೇವೆಗಳು":"services_offered",
  "ಐವಿಎಫ್ ಅನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ": "understanding_ivf",

  // Tamil
  "இலவச ஆலோசனை பதிவு செய்க": "book_consultation",
  "கர்ப்பகால கணிப்பான்": "success_calculator",
  "மருத்துவமனை கண்டுபிடி": "find_hospital",
  "அடிக்கடி கேட்கப்படும் கேள்விகள்":"frequently_asked_questions",
  //"உணர்ச்சி ஆதரவு": "emotional_support",
  "இஎம்ஐ வசதிகள்": "emi_facilities",
  "வெற்றி வீதம்": "success_rate",
  "ஐவிஎப் பாக்கேஜ்கள்": "packages",
  "வழங்கப்படும் சேவைகள்":"services_offered",
  "ஐவிஎப்பை புரிந்துகொள்ளவும்": "understanding_ivf",

  // Telugu
  "ఉచిత సలహా బుక్ చేయండి": "book_consultation",
  "గర్భధారణ కాలిక్యులేటర్": "success_calculator",
  "హాస్పిటల్ కనుగొనండి": "find_hospital",
  "తరచుగా అడిగే ప్రశ్నలు":"frequently_asked_questions",
  //"భావపూర్వక మద్దతు": "emotional_support",
  "ఇఎంఐ సౌకర్యాలు": "emi_facilities",
  "విజయ శాతం": "success_rate",
  "ఐవీఎఫ్ ప్యాకేజీలు": "packages",
  "అందించబడే సేవలు":"services_offered",
  "ఐవీఎఫ్ ను అర్థం చేసుకోండి": "understanding_ivf",

  // Bengali
  "ফ্রি পরামর্শ বুক করুন": "book_consultation",
  "গর্ভাবস্থা ক্যালকুলেটর": "success_calculator",
  "হাসপাতাল খুঁজুন": "find_hospital",
  "প্রায়শই জিজ্ঞাসিত প্রশ্নসমূহ":"frequently_asked_questions",
  //"মানসিক সহায়তা": "emotional_support",
  "ইএমআই সুবিধাসমূহ": "emi_facilities",
  "সফলতার হার": "success_rate",
  "আইভিএফ প্যাকেজসমূহ": "packages",
  "প্রদান করা সেবাসমূহ":"services_offered",
  "আইভিএফ বোঝা": "understanding_ivf",

  // Punjabi
  "ਮੁਫ਼ਤ ਸਲਾਹ ਬੁੱਕ ਕਰੋ": "book_consultation",
  "ਗਰਭਾਵਸਥਾ ਕੈਲਕੁਲੇਟਰ": "success_calculator",
  "ਹਸਪਤਾਲ ਲੱਭੋ": "find_hospital",
  "ਅਕਸਰ ਪੁੱਛੇ ਜਾਂਦੇ ਸਵਾਲ":"frequently_asked_questions",
  //"ਭਾਵਨਾਤਮਕ ਸਮਰਥਨ": "emotional_support",
  "ਈਐਮਆਈ ਸੁਵਿਧਾਵਾਂ": "emi_facilities",
  "ਸਫਲਤਾ ਦਰ": "success_rate",
  "ਆਈਵੀਆਫ ਪੈਕੇਜ": "packages",
  "ਪ੍ਰਦਾਨ ਕੀਤੀਆਂ ਜਾਣ ਵਾਲੀਆਂ ਸੇਵਾਵਾਂ":"services_offered",
  "ਆਈਵੀਆਫ ਨੂੰ ਸਮਝੋ": "understanding_ivf",

  // Assamese
  "বিনামূলীয়া পৰামৰ্শ বুক কৰক": "book_consultation",
  "গৰ্ভাৱস্থা কেলকুলেটৰ": "success_calculator",
  "হাস্পতাল বিচাৰক": "find_hospital",
  "সঘনাই সোধা প্ৰশ্নসমূহ":"frequently_asked_questions",
  //"ভাবগত সমৰ্থন": "emotional_support",
  "কিস্তিৰ সুবিধাসমূহ": "emi_facilities",
  "সফলতাৰ হাৰ": "success_rate",
  "আইভিএফ পেকেজসমূহ": "packages",
  "প্ৰদান কৰা সেৱাসমূহ":"services_offered",
  "আইভিএফ বুজা": "understanding_ivf",

  //Odia
  "ମୁଫ୍ତ ପରାମର୍ଶ ବୁକ୍ କରନ୍ତୁ": "book_consultation",
  "ଗର୍ଭାବସ୍ଥା କ୍ୟାଲକୁଲେଟର": "success_calculator",
  "ହସ୍ପିଟାଲ୍ ଖୋଜନ୍ତୁ": "find_hospital",
  "ପ୍ରାୟଶଃ ପଚରାଯାଉଥିବା ପ୍ରଶ୍ନଗୁଡ଼ିକ":"frequently_asked_questions",
  //"ଭାବନାତ୍ମକ ସମର୍ଥନ": "emotional_support",
  "ଇଏମଆଇ ସୁବିଧାଗୁଡ଼ିକ": "emi_facilities",
  "ସଫଳତା ହାର": "success_rate",
  "ଆଇଭିଏଫ ପ୍ୟାକେଜ୍‌ଗୁଡ଼ିକ": "packages",
  "ପ୍ରଦାନ କରାଯାଉଥିବା ସେବାଗୁଡ଼ିକ":"services_offered",
  "ଆଇଭିଏଫ ବୁଝନ୍ତୁ": "understanding_ivf",
};
