import time
from app.utils.llm_utils import ask_openai_validation_assistant


async def flow_check(msg: str, language: str):
    starttime = time.time()
    if language == "English":
        msg = msg.strip().lower()

    system_instruction = (
        "You are a strict classifier. understand the user question and intent and these rule serial number are just number for you don't return anything like 12 then medical_terms. Follow these rules in EXACT priority order:\n "
        "RULE 1 (highest priority, must override all others):\n"
        "- If input is name of the person or nick name of the person (like tia,alpha etc),indira ivf center name or clinic name, a number (like phone number),phone number(10 digits), pincode, Indira IVF center name, city, state, country, date like (2025-10-25 or in yyyy-mm-dd format) , address, time , "
        "or meaningless random text (like 'ewiufhifehiuwehfib' ,'abc xyz' ,'ewhdiwehciuwhc'), OR if the user refuses to provide information → RETURN None immediately.but if the type (indira ivf only then return faq_flow) . "
        "if the user enters text like 'answer in english','in english' then return language_change"
        "If the user asks anything related to the bot’s capabilities (what the bot can do, what it can answer), information about Indira IVF (including number of hospitals, IVF centers, locations, services, or general details), or any question about doctors—such as doctor names, number of doctors, best doctor, which doctor to consult, doctor availability, experience, specialization, or similar queries—in any language or phrasing, always classify the intent as faq_flow. This includes indirect, comparative, recommendation-based, or general doctor-related questions (e.g., ‘Who is the best doctor?’, ‘Which doctor should I consult?’, ‘Name of doctor at your center’)"
        "Do not check other rules if this condition is true.\n\n"
        "RULE 2: If the user asks  question  about IVF, Indira IVF, or about IVF-related Treatments or about bot working or About Indira IVf or about Hospital timings services or center timings opening or closing or number of Indira IVF Hospitals in india   or Facilites at Indira IVF( facilities like semen analysis,egg freezing,gender detmination test etc) or number of tests or different type of test (espcially gender determination test) provided by Indira IVF or if the user wants to know the advanced infertility treatment like LIT,PLI and which you mean that are frequently asked by users or the user ask about their condition then return (e.g. ivf-related queries, surrogacy, donor programs,conception,miscarriages,IVF treatment,about hospital,about Indira Ivf, about indira ivf  hospital,Where are your hospitals in India,indria ivf hospital or center timings or question regarding their pregnancy condition or ivf condition or their condition,docouments to be brought on first visit) or what is ivf or full form of ivf or if the users asks anything about infertility or anything about pregnancy or why the user is not getting pregnant or if the users is asking why to choose Indira IVF or (Is Indira IVF trustworthy?,What makes Indira IVF different?) → faq_flow"
        "RULE 3: If the user talks about loan, EMI, scheme  money, or bank-related things and if user is unable to afford ivf costs or the the user thinks that cost of ivf is high → loan_and_emi.\n but if the asks about intrest rate offered by indira ivf or what percent of intrest on loan offered by indira ivf or types of loan offered by Indira IVF or PLI then return faq_flow"
        "RULE 4: If the user talks about IVF calculation or wants to know their chances of IVF success → ivf_success_calculator.\n"
        "RULE 5: If the user talks about IVF or Indira IVF success rate or ivf successful cases → success_rate.\n but if the user want to know the success rate for a particular age then return faq_flow"
        "RULE 6: If the user talks about improving fertility, IVF lifestyle, preparations, or wants to improve chances of successful IVF → Lifestyle_and_Preparations.\n"
        "RULE 7: If the user mentions signing legal consent before IVF, or anything about consent forms, bonds, agreements or why do we have to fill form or anything related to consent form → legal_consent.\n"
        "RULE 8: If the user asks for the overall IVF journey / complete step-by-step cycle flow (full list of steps) in any language—e.g., “different steps in IVF cycle,” “steps in IVF cycle,” “IVF process step by step,” “Self oocyte cycle steps,” “Donor oocyte process,” “डोनर ओओसाइट की प्रक्रिया क्या है?”—then return ivf_steps; but if the user asks about any single step, sub-step, concept, definition, comparison, variants/types, timing, risks, eligibility, tests, medicines/injections, procedures, or details (including questions like “What are the Types of Embryo Transfers?”, “what is embryo transfer,” “embryo transfer kya hai,” “egg retrieval ka process,” “trigger injection kya hota hai,” “beta hCG test kaise hota hai”), or asks what is IVF / full form of IVF, or asks about cycles count, embryos count/type transferred, or asks for only one part of the process, then return faq_flow; when the question contains words like “types/kinds”, “what is”, “explain”, “details”, “kaise”, “kya hota hai”, “difference between” for any IVF-related step, it must be treated as faq_flow, and if there is any ambiguity or overlap, always prefer faq_flow over ivf_steps."
        "RULE 9: If the user asks only about the cost or packages of IVF — such as “IVF cost,” “IVF packages,” “IVF price,” “IVF EMI,” “how much IVF costs,” “Indira IVF cost,” or similar — then return cost_and_package.(Note: The question must be clearly and exclusively about IVF costs or IVF packages, not about other procedures or facilities.) but if the user asks about cost or any amount regarding iui or semen analysis or egg freezing facilities charges or what is included in this cost   like iui cost or cost of semen analysis or egg freezing chargs or if the users asks for first visit charges or consulation or check-up charges then return faq_flow"
        "RULE 10: If the user asks for emotional support or if the user is frightened or nervous about ivf or wants emotional support then return emotional_support but if the user give its own condition in ivf or if the user wants to know what support does Indira IVF provide then return faq_flow"
        "**-RULE 11: If the user asks only only about any tests or services or medical tests related query or IVF-related add-on services or services provided by Indira Ivf or Indira-IVF medical tests, advanced fertility tests, or specialized diagnostic procedures for both male and female  and specially this test (Anti-Müllerian Hormone (AMH)Test,Hormonal Profile Panel,Transvaginal Pelvic Ultrasound,Azoospermia Panel,NIPT (Non-Invasive Prenatal Testing),sFlt-1/PlGF Ratio) and services like(Endometrial Receptivity Analysis (ERA),Genetic Testing (PGT-A / PGT-M),Semen Analysis,Sperm DNA Fragmentation Test,Embryo Glue,Sperm Sorting Device,Laser Assisted Hatching,Blastocyst Culture,LIT (Lymphocyte Immunotherapy),TESA (Testicular Sperm Aspiration)) or if the user wants to know that these test or services are available at your center, then → add_on_service but if the user wants facilities like (egg freezing or semen analysis) then return faq_flow and if the user wants to get the education about ivf medical terms and procedures or treatments like Embryo Transfer etc or if the user wants to know the information about tests like (what is AMH, TESA,LIT) then return medical_terms"
        "RULE 12: If the user asks about ANY IVF-related medical terms for both male and female or any body organs related term Example(fallopian tube or uterine fibroids) all bodyparts which are helpful during ivf or any ivf related medical condition for both male and female (eg Adenomyosis, myomas)  or infertility-related medical procedure,terms, test, treatment, technology, diagnosis, or terminology for both male and female (examples include but are not limited to Embryo Transfer, Embryo Grading,Pregnancy test, Insemination, Embryo Freezing, Frozen Embryo Transfer (FET), Sperm collection, Egg retrieval, Fit for transfer, ICSI, PCOS, Endometrial Scratch, Hysteroscopy, Ovarian Stimulation, Luteal Phase Support, etc.) and if the users asks about Hormones & Medications(like estrogen,Estradiol etc),Embryology Terms,Uterine & Reproductive Terms Fertility Diagnostics or Outcomes & Complications→ medical_terms"
        "RULE 13:If the user asks a general nationwide informational query specifically about India (note not about indian states or city name if the user is asking for indian city or state then return nearby_centers but if for India as a country whole then return faq_flow) as a whole—such as total number of centers in India, centers across India, or nationwide clinic locations—AND “India” appears as a standalone word, then return faq_flow. If the user’s message contains any IVF-related keyword or name of hospitals or ivf centers/clinincs in certain area or pincode or  (centers, clinics, hospitals, branches, locations, offices, “Indira IVF centers”, “Indira IVF clinics”, “Indira IVF hospitals”) AND also contains a specific location other than the standalone word “India” (city, state, area, region, locality, pincode, “near me”, “nearby”, etc.) and this can be in any language, and if the users asks for the names of hospitals/ivf centers/clinic in any area  then return nearby_centers. If the user provides only a location without any IVF-related keyword or hospital related keyword, then return None."
        "RULE 14: If the user wants to cancel or reschedule its appointment then return cancel_or_reschedule but if the user wants to schedule the appointment then book_appointment "
        "Strict-RULE 15: If the user asks any question not related to  IVF or Indira IVF or fertility or any other irrelavant → out_of_context.\n"
        "RULE 16: If the user asks for or mentions contacting Indira IVF — including requests for:'customer care number', 'customer care no', 'Indira IVF number', 'helpline number', 'contact number', 'phone number', 'mobile number', 'emergency contact', or any general enquiry number — then classify as → emergency_contact.  However, if the user **provides a phone number** (i.e., a numeric value or 10-digit number) instead of asking for one, return → None."
        "RULE 17: If the user greets the bot or expresses courtesy (such as hello, hi, how are you, thanks, thank you, appreciate, ok thanks, etc.) in any language, classify it as greetings. If the user explicitly asks for general help or assistance using standalone words or short phrases (such as help, assist, guide, aid, encourage, uphold, मदद, etc.), also classify it as greetings. However, if the user asks about the bot’s capabilities, scope, or information it can provide (for example, ‘What can you do?’, ‘How can you help me?’, ‘What information can you give me?’, ‘What kind of questions can I ask?’), always classify it as faq_flow. Do not treat a person’s name as a greeting; return None in that case."
        "RULE 18:If the user wants the bot to speak or give the response in different language or if the user wants to change the language or also if the user message is some language name then also  (like hindi mein bolo,tell in english,answer in,answer in english ,in english etc) and it can also be like this in english,in hindi etc then return -> language_change"
        "RULE 19:If the user wants the patient testimonials or the videos of the patient od if the user wants to know the story of patient then return -> patient_testimonals"
        "Return ONLY one exact word from this list:\n"
        "book_appointment, ivf_success_calculator, Lifestyle_and_Preparations, loan_and_emi, "
        "emergency_contact, success_rate, legal_consent,ivf_steps,emotional_support,out_of_context,medical_terms,add_on_service,faq_flow,nearby_centers,cancel_or_reschedule,greetings,language_change,patient_testimonals,None\n"
        "(case-sensitive, no quotes, no explanations)."
    )

    prompt = f"{system_instruction}\n\nQuestion: {msg}"

    answer = await ask_openai_validation_assistant(
        prompt=prompt,
        max_tokens=10,
    )
    return answer


async def new_language_change(content: str):
    prompt = f"You are a Language Detector return the language name the user wants or the language name in which the user wants the answer and the language name written in that particular language only and give me only language name fromt his message={content} output:string"
    answer = await ask_openai_validation_assistant(
        prompt=prompt,
        max_tokens=10,
    )
    return answer
